#!/usr/bin/env python3
"""make-manifest.py — generate the single published manifest for a release.

One file is consumed by two very different clients, which is the whole point:

  - The **device**, in `otaFetchLatest()` (§25). It reads the flat top-level
    `version`, `firmware_sha` and `firmware_url` keys. Those must stay exactly
    where they are, or firmware already in the field stops seeing updates.
  - The **web installer**, which needs every transport plus the filesystem image,
    with offsets, so a browser can flash a blank board.

Both read the same generated file, so they cannot offer different versions. That
is the alignment this script exists to guarantee — the previous arrangement had
the manifest hand-written, which is exactly how a firmware and its manifest drift
apart.

`littlefs_url` / `littlefs_sha` are published even though today's
`otaFetchLatest()` ignores them: the firmware already accepts a `littlefs_url` via
its local `POST /api/ota/update` endpoint and the remote command queue, so an app
can push a filesystem update, and extending the self-service path is then a
firmware change with no release-process change needed.

Usage:
    python3 scripts/make-manifest.py --version 2.3.0 --repo owner/name \\
        --ota-env esp32s3_hsu --dist dist --out pages/version.json
"""

import argparse
import hashlib
import json
import os
import sys

# Kept in step with partitions.csv. The web installer needs these to place each
# image; getting one wrong bricks a board, so they are written down once here
# rather than repeated in the installer's own HTML.
OFFSETS = {
    "bootloader": "0x0000",
    "partitions": "0x8000",
    "boot_app0": "0xE000",
    "app": "0x10000",
    "filesystem": "0x650000",
}

# Every transport that gets published, with what a human needs to pick one.
TRANSPORTS = [
    ("esp32s3_hsu", "hsu", 2, "UART (HSU) — reference build, bench-verified"),
    ("esp32s3",     "spi", 2, "SPI — compiles, not bench-verified"),
    ("esp32s3_i2c", "i2c", 1, "I2C on Wire1 — single reader, fixed 0x24 address"),
]


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", required=True)
    ap.add_argument("--repo", required=True, help="owner/name")
    ap.add_argument("--ota-env", required=True, help="env whose binary the OTA channel serves")
    ap.add_argument("--dist", default="dist")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    base = "https://github.com/%s/releases/download/v%s" % (args.repo, args.version)

    def entry(filename):
        path = os.path.join(args.dist, filename)
        if not os.path.exists(path):
            print("ERROR: missing release asset: %s" % path, file=sys.stderr)
            sys.exit(1)
        return {
            "url": "%s/%s" % (base, filename),
            "sha256": sha256(path),
            "size": os.path.getsize(path),
        }

    fs = entry("littlefs.bin")

    builds = {}
    for env, transport, readers, description in TRANSPORTS:
        app = entry("firmware-%s.bin" % env)
        factory = entry("firmware-%s.factory.bin" % env)
        builds[env] = {
            "transport": transport,
            "readers": readers,
            "description": description,
            # firmware.bin replaces the app partition only — this is what OTA uses.
            "firmware_url": app["url"],
            "firmware_sha": app["sha256"],
            "firmware_size": app["size"],
            "firmware_offset": OFFSETS["app"],
            # factory.bin is the merged image for a first flash of blank hardware.
            # NEVER hand this to Update.begin(): it spans 0x0000 upward and would
            # overwrite the bootloader and partition table.
            "factory_url": factory["url"],
            "factory_sha": factory["sha256"],
            "factory_size": factory["size"],
            "factory_offset": OFFSETS["bootloader"],
        }

    if args.ota_env not in builds:
        print("ERROR: --ota-env %r is not a published transport" % args.ota_env, file=sys.stderr)
        sys.exit(1)
    ota = builds[args.ota_env]

    manifest = {
        "_comment": (
            "Generated by scripts/make-manifest.py — never hand-edit. The flat "
            "version/firmware_url/firmware_sha keys are what the device's "
            "otaFetchLatest() reads; do not move or rename them. `builds` carries "
            "every transport for the web installer."
        ),
        # --- read by the device (otaFetchLatest) -------------------------------
        "version": args.version,
        "firmware_url": ota["firmware_url"],
        "firmware_sha": ota["firmware_sha"],
        # Published for the filesystem-capable update paths. The device accepts a
        # littlefs_url via POST /api/ota/update and the Firestore command queue.
        "littlefs_url": fs["url"],
        "littlefs_sha": fs["sha256"],
        # --- read by the web installer ---------------------------------------
        "ota_env": args.ota_env,
        "release_url": "https://github.com/%s/releases/tag/v%s" % (args.repo, args.version),
        "notes_url": "https://github.com/%s/blob/main/docs/release-notes/v%s.md" % (
            args.repo, args.version),
        "offsets": OFFSETS,
        "filesystem": {
            "url": fs["url"],
            "sha256": fs["sha256"],
            "size": fs["size"],
            "offset": OFFSETS["filesystem"],
        },
        "builds": builds,
    }

    os.makedirs(os.path.dirname(os.path.abspath(args.out)) or ".", exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2)
        fh.write("\n")

    print("wrote %s" % args.out)
    print("  version:    %s" % args.version)
    print("  ota env:    %s" % args.ota_env)
    print("  transports: %s" % ", ".join(builds))
    print("  filesystem: %d bytes" % fs["size"])
    return 0


if __name__ == "__main__":
    sys.exit(main())
