#!/usr/bin/env bash
# update_toc.sh — regenerate the table of contents inside the firmware .ino.
#
# Section banners look like:   // §N — SECTION NAME
# The TOC block between "// --- TOC BEGIN" and "// --- TOC END" is rebuilt from
# them, so adding, moving or renaming a section only ever needs this one run.
#
# Usage: bash scripts/update_toc.sh
#
# Portability: works on macOS's bash 3.2 (no mapfile, no associative arrays)
# and with BSD or GNU grep/sed/awk alike (no grep -P).
#
# History worth knowing: this script used to match the literal mojibake
# sequence the § had decayed into, rather than the § itself — the corruption
# had been encoded into the tooling instead of fixed, which is why the TOC it
# produced was itself corrupt, and why the two sections written in a different
# banner format (§5, §AUDIO) were silently never listed.

set -uo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INO="$ROOT/TigerTagSplashESP32/TigerTagSplashESP32.ino"

[ -f "$INO" ] || { echo "ERROR: $INO not found" >&2; exit 1; }

FILE_LINES=$(awk 'END{print NR}' "$INO")

# Section markers, after line 50 so the TOC's own lines are never re-scanned.
# Output: line number <TAB> section name (the "§N — " prefix stripped).
MARKERS=$(awk 'NR > 50 && /^\/\/ §[^ ]+ — / {
    line = $0
    sub(/^\/\/ §[^ ]+ — /, "", line)
    sub(/[ \t]+$/, "", line)
    print NR "\t" line
}' "$INO")

if [ -z "$MARKERS" ]; then
  echo "ERROR: no '// §N — TITLE' section markers found." >&2
  echo "       Banners must use exactly that form — see docs/FIRMWARE.md." >&2
  exit 1
fi

COUNT=$(printf '%s\n' "$MARKERS" | awk 'END{print NR}')
echo "Found $COUNT section markers."

# Each section spans from its own line to the line before the next marker; the
# last one runs to end of file.
BODY=$(printf '%s\n' "$MARKERS" | awk -F'\t' -v total="$FILE_LINES" '
{ sline[NR] = $1; name[NR] = $2 }
END {
    for (i = 1; i <= NR; i++) {
        end = (i < NR) ? sline[i+1] - 1 : total
        printf "//   %-52s %5d-%5d\n", name[i], sline[i], end
    }
}')

printf '%s\n' "$BODY" | sed 's|^//   |  |'

TOC_BEGIN=$(grep -n '// --- TOC BEGIN' "$INO" | head -1 | cut -d: -f1)
TOC_END=$(grep -n '// --- TOC END'   "$INO" | head -1 | cut -d: -f1)

if [ -z "$TOC_BEGIN" ] || [ -z "$TOC_END" ]; then
  echo "ERROR: TOC BEGIN/END markers missing from the .ino" >&2
  exit 1
fi

TMP="$INO.tmp.$$"
{
  head -n "$(( TOC_BEGIN - 1 ))" "$INO"
  echo "// --- TOC BEGIN (auto-generated by scripts/update_toc.sh) ---"
  echo "//"
  echo "//   TABLE OF CONTENTS                                     line range"
  echo "//   ---------------------------------------------------- -----------"
  printf '%s\n' "$BODY"
  echo "//"
  echo "//   To regenerate:  bash scripts/update_toc.sh"
  echo "// --- TOC END -----------------------------------------------"
  tail -n "+$(( TOC_END + 1 ))" "$INO"
} > "$TMP" && mv "$TMP" "$INO"

echo "TOC updated (replaced lines $TOC_BEGIN-$TOC_END)."
